apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-dpl
spec:
  replicas: 4 
  selector:
    matchLabels:
      app: nginx-dpl
  template:
    metadata:
      labels:
        app: nginx-dpl
    spec:
      containers:
      - name: nginx-dpl
        #image: nginx:latest 
        image: 69966/earthdx:78
        ports:
        - containerPort: 80
